name: 'Transfer Issue'
description: 'Transfers github issue from github repo to another github repo'
inputs:
  repo-source:
    description: 'repo to copy from'
    required: true
  repo-destination:
      description: 'repo to copy to'
      required: true
#outputs:
#  time: # output will be available to future steps
#    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
